In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
np.cumsum(arr) 

array([ 1,  3,  6, 10, 15], dtype=int32)

In [5]:
np.cumprod(arr) 

array([  1,   2,   6,  24, 120], dtype=int32)

In [6]:
sr = pd.Series([1,2,3,4,5]) 
sr

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
np.cumsum(sr) 

0     1
1     3
2     6
3    10
4    15
dtype: int64

In [8]:
np.cumprod(sr) 

0      1
1      2
2      6
3     24
4    120
dtype: int64

In [9]:
sr.cumsum() 

0     1
1     3
2     6
3    10
4    15
dtype: int64

In [10]:
sr.cumprod() 

0      1
1      2
2      6
3     24
4    120
dtype: int64

In [11]:
df = pd.DataFrame( [[1,2,3,4,5],[6,7,8,9,10]]) 

In [12]:
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [13]:
df.cumsum() 

0  1   2   3   4
0  1  2   3   4   5
1  7  9  11  13  15

In [14]:
df.cumprod() 

0   1   2   3   4
0  1   2   3   4   5
1  6  14  24  36  50