In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt?

In [5]:
np.sqrt(arr) 

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [6]:
x = np.random.rand(10)
y = np.random.rand(10) 

In [7]:
x

array([ 0.16169749,  0.41675699,  0.61871391,  0.25054125,  0.89778002,
        0.03989634,  0.62315911,  0.22478615,  0.84576466,  0.90152568])

In [8]:
y

array([ 0.62915985,  0.1254282 ,  0.03952811,  0.48143937,  0.22120451,
        0.30272047,  0.38431483,  0.58571776,  0.12733512,  0.7091503 ])

In [9]:
np.maximum(x,y) 

array([ 0.62915985,  0.41675699,  0.61871391,  0.48143937,  0.89778002,
        0.30272047,  0.62315911,  0.58571776,  0.84576466,  0.90152568])

In [10]:
np.maximum?

In [11]:
arr2 = np.random.randn(6,5) 
arr2

array([[-0.58997706,  0.16696598, -1.20856177, -1.30151535, -0.54976406],
       [ 0.26182453,  0.79549312,  0.41247747,  1.46473534,  0.65216867],
       [ 0.02981262,  0.6011785 , -1.24392192, -1.54219354,  0.74143129],
       [-0.55064125,  2.28968461,  0.23419797, -0.68689166,  0.19475991],
       [ 1.24317139,  0.68416749,  0.12527053,  0.51839348, -1.22820917],
       [-0.75563759, -0.13915964, -0.24067349,  0.78165028,  0.41495349]])

In [12]:
arr2.sum() 

1.5751901763017906

In [13]:
arr2.mean() 

0.052506339210059684

In [14]:
arr2.sum(axis=0)

array([-0.36144735,  4.39833007, -1.92121121, -0.76582147,  0.22534013])

In [15]:
arr2.sum(axis=1)

array([-3.48285226,  3.58669914, -1.41369305,  1.48110958,  1.34279372,
        0.06113305])

In [16]:
arr2 > 0

array([[False,  True, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [False, False, False,  True,  True]], dtype=bool)

In [17]:
(arr2 > 0).sum() 

18

In [18]:
arr3 = np.random.randn(7) 

In [19]:
arr3

array([-0.19133627, -2.84696279, -0.53768067, -0.40994129,  0.28992961,
       -0.51466388,  0.21669514])

In [20]:
arr3.sort?

In [21]:
arr3.sort() 

In [22]:
arr3

array([-2.84696279, -0.53768067, -0.51466388, -0.40994129, -0.19133627,
        0.21669514,  0.28992961])

In [23]:
np.sort(arr3)

array([-2.84696279, -0.53768067, -0.51466388, -0.40994129, -0.19133627,
        0.21669514,  0.28992961])

In [24]:
np.sort(arr3)[::-1] 

array([ 0.28992961,  0.21669514, -0.19133627, -0.40994129, -0.51466388,
       -0.53768067, -2.84696279])

In [25]:
arr4 = np.random.randn(5,3) 
arr4

array([[ 0.99315579,  1.28183059, -0.84511149],
       [ 0.53656613, -0.08375967, -0.22887833],
       [-0.67505975, -0.01445389, -0.15392802],
       [-0.30136736,  0.4506178 ,  0.80402991],
       [ 0.34467309,  1.02967196,  1.36555348]])

In [26]:
np.sort(arr4, axis=0) 

array([[-0.67505975, -0.08375967, -0.84511149],
       [-0.30136736, -0.01445389, -0.22887833],
       [ 0.34467309,  0.4506178 , -0.15392802],
       [ 0.53656613,  1.02967196,  0.80402991],
       [ 0.99315579,  1.28183059,  1.36555348]])

In [27]:
np.sort(arr4, axis=1) 

array([[-0.84511149,  0.99315579,  1.28183059],
       [-0.22887833, -0.08375967,  0.53656613],
       [-0.67505975, -0.15392802, -0.01445389],
       [-0.30136736,  0.4506178 ,  0.80402991],
       [ 0.34467309,  1.02967196,  1.36555348]])

In [28]:
np.sort(arr4, axis=1)[::-1] 

array([[ 0.34467309,  1.02967196,  1.36555348],
       [-0.30136736,  0.4506178 ,  0.80402991],
       [-0.67505975, -0.15392802, -0.01445389],
       [-0.22887833, -0.08375967,  0.53656613],
       [-0.84511149,  0.99315579,  1.28183059]])

In [29]:
np.sort(arr4, axis=0)[::-1] 

array([[ 0.99315579,  1.28183059,  1.36555348],
       [ 0.53656613,  1.02967196,  0.80402991],
       [ 0.34467309,  0.4506178 , -0.15392802],
       [-0.30136736, -0.01445389, -0.22887833],
       [-0.67505975, -0.08375967, -0.84511149]])

In [30]:
names = np.array(["sunyoung", "pyo", "sunny", "sunyoung", "pyo", "sunny", "sunyoung"])
value = np.array([3,3,3,2,2,1,1,4,4])

In [31]:
np.unique(names)

array(['pyo', 'sunny', 'sunyoung'],
      dtype='<U8')

In [32]:
np.unique(value) 

array([1, 2, 3, 4])